# NOTE: THIS IS JUST TO MAKE IT EASIER TO RUN THE PROGRAM ON COMMAND WHILE I'M #
	# WORKING IN VIM. IF YOU DOWNLOADED THIS PROJECT AND ARE JUST TESTING IT, #
	# RUN THE EXECUTABLES IN THE ./bin/debug DIRECTORY! #

import os
os.system("./bin/debug/LobsterEngine.elf")
